<?php

namespace App\Models;

use App\Enum\ReminderFrequency;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Reminder extends Model
{
    protected $fillable = [
        'user_id',
        'dev_rel',
        'title',
        'message',
        'start_date',
        'last_sent',
        'sending_frequency',
        'pause',
    ];

    protected $casts = [
        'dev_rel' => 'boolean',
        'last_sent' => 'date',
        'sending_frequency' => ReminderFrequency::class,
    ];

    protected static function booted()
    {
        parent::booted(); // TODO: Change the autogenerated stub

        static::creating(function ($reminder) {
            if (! $reminder->user_id) {
                $reminder->user_id = auth()->id();
            }
        });
    }

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }
}
